.ONESHELL:
debian-package:
	python setup.py --command-packages=stdeb.command sdist_dsc
	cd deb_dist/es-bgm-*

	cp ../../DEBIAN/postinst debian/
	cp ../../DEBIAN/postrm debian/

# Replace the standards version generated by stdeb to make lintian pass the version check
	sed -i 's/Standards-Version: 3\.9\.6/Standards-Version: 3\.9\.8/g' debian/control

	debuild

tests:
	python setup.py test
