#!/bin/bash

set -e

echo "Enabling background music daemon..."
systemctl daemon-reload
systemctl enable bgm
systemctl start bgm

echo "Done. Please restart EmulationStation to hear your music :)"

#DEBHELPER#